function [T,V,P] = acc2trap(Accel,dt)

% [T,V,P] = acc2trap(Accel,dt)
%
% Calculate a shaped trapezoidal trajectory (both 
% velocity and position) using an acceleration table
% The table is generated by GETACCEL.
%
% Parameters:
% Accel - Acceleration Table from GETACCEL
% dt - time step for system (sec/step)
%
% Returns:
% T - A time vector [0 dt 2dt ....];
% V - A velocity vector.
% P - A position vector.
% All outputs have the same length.
%
% See also GETACCEL.
%


index = 1;
vel = 0;
pos = 0;

for nn=1:Accel(length(Accel),1)+1,
  if nn == Accel(index,1)+1,
    acc = Accel(index,2);
    index = index + 1;
  end
  vel = vel+acc;
  pos = pos+dt*vel;
  V(nn) = vel;
  P(nn) = pos;
end

% We need a time vector.
T = (0:dt:(length(V)-1)*dt)';
